updated polymer library

diff --git a/web/lib/iron-resizable-behavior/.travis.yml b/web/lib/iron-resizable-behavior/.travis.yml
--- a/web/lib/iron-resizable-behavior/.travis.yml
+++ b/web/lib/iron-resizable-behavior/.travis.yml
@@ -1,5 +1,5 @@
 language: node_js
-sudo: required
+sudo: 'false'
 before_script:
   - npm install -g polymer-cli
   - polymer install --variants
@@ -7,23 +7,25 @@ before_script:
     npm run update-types && git diff --exit-code || (echo -e
     '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
     update-types".' && false)
+  - >-
+    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
+    Project is not formatted. Please run "npm run format".' && false)
 env:
   global:
     - secure: >-
-        Bsp8pa19FCij3Eee0P5eOE8ZrbylrYL99R9EIxH6rcDH+rxMhK0BIfSiXTPSFRk2iqJp++RIZN8kUu5GddetiXreRZDtnhXBA2QoYteIAS8Hzy9u2EggqI0UdGqbCiFHDVD/rEQyhSPiIfWHGCg/Moeo9J2k/eC2w6I8I9C15Zw=
+        Oqxdd+qGvPupU4boPps+T1LvbxCYDYTSFUCcJybasEnQ+mooUn1tF8FhSZNtZyjgygjb+GYjlx0OdXuHUTOdv+ubPk0ilQmxc+9O0Fh4Dwa2dUNy4WaBHNpTfeWtwDlv8NOZyC+HuUQmDUD9xw1BPla2sZoAdGWSJ5qnQUwgUn4=
     - secure: >-
-        j9xIW/banUkkNaLrWVGcTsasAp64zEmZJQO+eY8ExINx3uLbDh5h6Foc7xWhJ4Yu7aey3+nH5BWKYimtPTYoXUD2nIWU31yBNbqU/+G6vIppDbgPHMRcVnRiO7YZ0yW1JunvKs+1lOPhOw4ibztJjGkQ2ZK9q6ZSJvQKRbo6Au0=
-node_js: stable
+        E3iy+4Gsp27GEeNg7yHlcR/5Gmm3nldvJKIgPeNxcWYFoqqnpe+iOt/GY5YqevIe3FSZ4O1d5Yw2SalTTOiWIliGy99skGO/ItjhaE3mNnYmqRisB7zpdQBMCoYSV3Qh8IHVbgOzl/cWL0FUXVORTjYs2VQ19yivqC/RaNVwi9k=
+node_js: '9'
 addons:
   firefox: latest
-  apt:
-    sources:
-      - google-chrome
-    packages:
-      - google-chrome-stable
+  chrome: stable
 script:
   - xvfb-run polymer test
   - >-
     if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
     fi
 dist: trusty
+cache:
+  directories:
+    - node_modules
